try {
    let x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    console.log(x)
    console.log(y)
}
catch (e) {
    console.log("This is error which shows :" + e.message)
}